{
 "title": "Service Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level,job) (log_statements_total{level!=\"error\",level!=\"warning\"})",
     "legendFormat": "{{job}} - {{level}}"
    }
   ]
  },
  {
   "title": "Log count - Warnings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level,job) (log_statements_total{level=\"warning\"})",
     "legendFormat": "{{job}} - {{level}}"
    }
   ]
  },
  {
   "title": "Log count - Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level,job) (log_statements_total{level=\"error\"})",
     "legendFormat": "{{job}} - {{level}}"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (sum (rate(log_statements_total{}[1m])) by (instance,job)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Approximate Order Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (orders{}) by (status)", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Approximate Stock Reservations",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (reservations{})" }
   ]
  },
  {
   "title": "Requests Orders",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,method,url) (requests_total{error=\"\",method=~\".*[Oo]rder.*\",method!=\"GetOrder\"} or requests_total{method=\"SendEmail\"} or requests_total{method=\"CompleteReservation\"} or requests_total{method=\"ReserveArticles\"})",
     "legendFormat": "{{job}}-{{method}}{{url}}"
    }
   ]
  },
  {
   "title": "Orders Total",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (orders{})", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Avg Articles over Instances",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (articles{}) by (name,category)",
     "legendFormat": "{{name}} - {{category}}"
    }
   ]
  },
  {
   "title": "Requests Total - Other",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,method,url) (requests_total{error=\"\",method!~\".*[Oo]rder.*\",method!=\"CompleteReservation\",method!=\"ReserveArticles\",method!=\"SendEmail\"} or gin_requests_total{code=~\"^(2).+\",url!=\"/favicon.ico\"})",
     "legendFormat": "{{job}}-{{method}}{{url}}"
    }
   ]
  },
  {
   "title": "Increase Circuit Breaker Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(circuit_breaker_states{}[1m])) by (name,status)",
     "legendFormat": "{{name}}, {{status}}"
    }
   ]
  },
  {
   "title": "Requests Total - Errors",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,method,url,code) (requests_total{error!=\"\"} or gin_requests_total{code!~\"^(2).+\",code!=\"404\",code!=\"400\",url!=\"/favicon.ico\"})",
     "legendFormat": "{{job}}-{{method}}{{url}}-{{error}}{{code}}"
    }
   ]
  },
  {
   "title": "API-Gateway",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by (code,method,url) (increase(gin_requests_total{job=\"api-gateway\",url!=\"/favicon.ico\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Cart Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"cart\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Order Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (method) (increase(requests_total{job=\"order\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Stock Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by (method) (increase(requests_total{job=\"stock\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Shipment Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"shipment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Catalogue Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"catalogue\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Email Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"e-mail\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Payment Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"payment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Currency Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"currency\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Supplier Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum by (method,error) (increase(requests_total{job=\"supplier\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests Total - Errors - Detail",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,method,url,error,code) (requests_total{error!=\"\"})",
     "legendFormat": "{{job}}-{{method}}{{url}}-{{error}}{{code}}"
    }
   ]
  },
  {
   "title": "Logs - All",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "measurement": "logrus",
     "query": "SELECT * FROM \"logrus\" ",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}