// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatalogueClient is the client API for Catalogue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogueClient interface {
	GetArticles(ctx context.Context, in *RequestArticles, opts ...grpc.CallOption) (*ResponseArticles, error)
}

type catalogueClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogueClient(cc grpc.ClientConnInterface) CatalogueClient {
	return &catalogueClient{cc}
}

func (c *catalogueClient) GetArticles(ctx context.Context, in *RequestArticles, opts ...grpc.CallOption) (*ResponseArticles, error) {
	out := new(ResponseArticles)
	err := c.cc.Invoke(ctx, "/catalogue.Catalogue/GetArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogueServer is the server API for Catalogue service.
// All implementations must embed UnimplementedCatalogueServer
// for forward compatibility
type CatalogueServer interface {
	GetArticles(context.Context, *RequestArticles) (*ResponseArticles, error)
	mustEmbedUnimplementedCatalogueServer()
}

// UnimplementedCatalogueServer must be embedded to have forward compatible implementations.
type UnimplementedCatalogueServer struct {
}

func (UnimplementedCatalogueServer) GetArticles(context.Context, *RequestArticles) (*ResponseArticles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticles not implemented")
}
func (UnimplementedCatalogueServer) mustEmbedUnimplementedCatalogueServer() {}

// UnsafeCatalogueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogueServer will
// result in compilation errors.
type UnsafeCatalogueServer interface {
	mustEmbedUnimplementedCatalogueServer()
}

func RegisterCatalogueServer(s grpc.ServiceRegistrar, srv CatalogueServer) {
	s.RegisterService(&Catalogue_ServiceDesc, srv)
}

func _Catalogue_GetArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestArticles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogueServer).GetArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogue.Catalogue/GetArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogueServer).GetArticles(ctx, req.(*RequestArticles))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalogue_ServiceDesc is the grpc.ServiceDesc for Catalogue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalogue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogue.Catalogue",
	HandlerType: (*CatalogueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticles",
			Handler:    _Catalogue_GetArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalogue.proto",
}
