
### Successful test: check response status is 200
GET localhost:50000/articles
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET http://localhost:50000/articles?category=hardware
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET http://localhost:50000/articles?category=sport
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET http://localhost:50000/articles?category=office
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}