### Send POST request with json body
POST http://localhost/cart
Content-Type: application/json

{
  "article_id": "put_here_your_article_id"
}

### Successful test: check response status is 200
GET localhost/cart/your_cart_id
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
PUT localhost/cart/your_cart_id
Content-Type: application/json

{
  "article_id": "put_here_your_article_id"
}