### Send POST request with json body
POST http://localhost/cart
Content-Type: application/json

{
  "article_id": "61bc5ac5c1500ae51b83fb1a"
}

### Successful test: check response status is 200
GET localhost/cart/1
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}