
### Successful test: check response status is 200
GET localhost/exchange/USD
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/PLN
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/GBP
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/INR
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/CAS
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/JPY
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET localhost/exchange/SEK
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Failed test: check response status is 400
GET localhost/exchange/notwork
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 200");
});
%}

### Failed test: check response status is 400
GET localhost/exchange/notwork2
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 200");
});
%}