
### 1. Step: Get articles
GET localhost/articles
Accept: application/json

### 2. Step: Choose an article to buy and create a cart
POST http://localhost/cart
Content-Type: application/json

{
  "article_id": "put_here_your_article_id"
}

### 3. Step: You can add articles to your cart with an articleID and your new cartID
PUT localhost/cart/your_cart_id
Content-Type: application/json

{
  "article_id": "put_here_your_article_id"
}

### 4. Step: After adding articles to your cart you can create an order.
POST http://localhost/order
Content-Type: application/json

{
  "cartId": "your_cart_id",
  "address": "Muster-Allee 42",
  "name": "Max Mustermann",
  "creditCard": "123456789-123",
  "email": "max.mustermann@web.de"
}

### 5. Step: Look at your orders status with your new orderID
GET localhost/order/your_order_id
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}